.package-and-qa-base:
  image: ruby:2.6-alpine
  stage: qa
  before_script: []
  needs: ["build-qa-image", "gitlab:assets:compile pull-cache"]
  dependencies: []
  cache: {}
  variables:
    GIT_DEPTH: "1"
  retry: 0
  script:
    - source scripts/utils.sh
    - install_gitlab_gem
    - ./scripts/trigger-build omnibus
  only:
    - branches@gitlab-org/gitlab-ce
    - branches@gitlab-org/gitlab-ee
  except:
    - master

package-and-qa-manual:
  extends: .package-and-qa-base
  when: manual
  except:
    - master
    - /(^docs[\/-].+|.+-docs$)/
    - /(^qa[\/-].*|.*-qa$)

package-and-qa:
  extends: .package-and-qa-base
  allow_failure: true
  only:
    - /(^qa[\/-].*|.*-qa$)/@gitlab-org/gitlab-ce
    - /(^qa[\/-].*|.*-qa$)/@gitlab-org/gitlab-ee
